### ISSUE TITLE
command line print "TypeError: cannot read the property 'src' of null

### ISSUE THREAD

**Issue by cnscorpions** [ismnoiet/dribbble-downloader#1]
Hi, something's wrong. 

code is as follows:

```C:\Users\ASUS>dribbble-downloader https://dribbble.com/shots/2262761-Mobile-Blog-App-Interface/attachments/424147
C:\Users\ASUS\AppData\Roaming\npm\node_modules\dribbble-downloader\Dribbble.js:49
          that.mainImgUrl = mainImgUrl.src
                                      ^

TypeError: Cannot read property 'src' of null
    at Object.done (C:\Users\ASUS\AppData\Roaming\npm\node_modules\dribbble-downloader\Dribbble.js:49:39)
    at process.nextTick (C:\Users\ASUS\AppData\Roaming\npm\node_modules\dribbble-downloader\node_modules\jsdom\lib\jsdom.js:325:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

C:\Users\ASUS>
```
pls help work it out, thanks :)

**Comment by ckhawks** [comment]
Having this issue too.

**Comment by mauriciabad** [comment]
I have the same issue

**Comment by a2zquizanswers** [comment]
Yeah, doesn't look like its been fixed at all. Any other developers have any insights into how to resolve this?
